/**
 * EXPORT SERVICE
 *
 * Client-side data portability utility providing RFC 4180 CSV export
 * and Logiqx XML DAT generation for integration with ROM managers (igir, clrmamepro).
 */

import { Injectable } from '@angular/core';
import {
  Game,
  Toy,
  OwnershipStatus,
  PlayStatus,
} from '../models/collection.models';

@Injectable({
  providedIn: 'root',
})
export class ExportService {
  /**
   * Generates an RFC 4180-compliant CSV string and triggers a browser file download.
   *
   * @param items Array of Game or Toy objects
   * @param type 'games' | 'toys'
   * @param filename Custom filename or auto-generated default
   */
  public exportCsv(
    items: (Game | Toy)[],
    type: 'games' | 'toys',
    filename?: string,
  ): void {
    const csvContent = this.generateCsv(items, type);
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const defaultName =
      filename ||
      `gagglog-${type}-export-${new Date().toISOString().slice(0, 10)}.csv`;
    this.triggerDownload(blob, defaultName);
  }

  /**
   * Generates a Logiqx XML DAT string and triggers a browser file download.
   * Logiqx DATs can be directly consumed by igir, clrmamepro, and RomVault.
   *
   * @param games Array of Game objects
   * @param headerName Title of the DAT file
   * @param filename Custom filename or auto-generated default
   */
  public exportLogiqxXmlDat(
    games: Game[],
    headerName: string = 'Gagglog Collection Wishlist',
    filename?: string,
  ): void {
    const xmlContent = this.generateLogiqxXmlDat(games, headerName);
    const blob = new Blob([xmlContent], {
      type: 'application/xml;charset=utf-8;',
    });
    const defaultName =
      filename ||
      `gagglog-dat-export-${new Date().toISOString().slice(0, 10)}.dat`;
    this.triggerDownload(blob, defaultName);
  }

  /**
   * Builds an RFC 4180 compliant CSV string from games or toys.
   */
  public generateCsv(items: (Game | Toy)[], type: 'games' | 'toys'): string {
    if (type === 'games') {
      const headers = [
        'Title',
        'Platform',
        'Series',
        'Canonical Series',
        'Region',
        'Ownership Status',
        'Play Status',
        'Backup Status',
        'Release Date',
        'ROM Filename',
        'ROM CRC',
        'Price Loose ($)',
        'Price CIB ($)',
        'Price New ($)',
        'Retail Price ($)',
        'Retail On Sale',
        'Barcode',
        'Variants',
      ];

      const rows = (items as Game[]).map((g) => [
        g.title || '',
        g.display_name || g.platform || '',
        g.series || '',
        g.canonical_series || '',
        g.region || '',
        this.getOwnershipLabel(g.ownership_status),
        this.getPlayStatusLabel(g.play_status),
        g.backup_status ? 'Backed Up' : 'Missing',
        g.release_date || '',
        g.rom_name || '',
        g.rom_crc || '',
        g.price_loose ? (g.price_loose / 100).toFixed(2) : '',
        g.price_cib ? (g.price_cib / 100).toFixed(2) : '',
        g.price_new ? (g.price_new / 100).toFixed(2) : '',
        g.retail_price ? (g.retail_price / 100).toFixed(2) : '',
        g.retail_on_sale ? 'Yes' : 'No',
        g.barcode || '',
        g.variants || '',
      ]);

      return this.formatCsvTable([headers, ...rows]);
    } else {
      const headers = [
        'Name',
        'Line',
        'Series',
        'Type',
        'Region',
        'Ownership Status',
        'Release Date',
        'Price Loose ($)',
        'Amiibo ID',
      ];

      const rows = (items as Toy[]).map((t) => [
        t.name || '',
        t.line || '',
        t.series_name || t.series || '',
        t.type || '',
        t.region || '',
        this.getOwnershipLabel(t.ownership_status),
        t.release_date || '',
        t.price_loose ? (t.price_loose / 100).toFixed(2) : '',
        t.amiibo_id || '',
      ]);

      return this.formatCsvTable([headers, ...rows]);
    }
  }

  /**
   * Builds a Logiqx XML DAT string from game entries.
   */
  public generateLogiqxXmlDat(
    games: Game[],
    headerName: string = 'Gagglog Collection Wishlist',
  ): string {
    const today = new Date().toISOString().slice(0, 10);
    const lines: string[] = [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE datafile PUBLIC "-//Logiqx//DTD ROMs//EN" "http://www.logiqx.com/Dats/datafile.dtd">',
      '<datafile>',
      '  <header>',
      `    <name>${this.escapeXml(headerName)}</name>`,
      `    <description>${this.escapeXml(headerName)} generated by Gagglog Collection Tracker</description>`,
      `    <version>${today}</version>`,
      `    <date>${today}</date>`,
      '    <author>Gagglog Collection Tracker</author>',
      '    <homepage>https://github.com/wesd92/collection-tracker</homepage>',
      '  </header>',
    ];

    for (const game of games) {
      // Prioritize clean ROM filename when present, falling back to game title
      const gameNodeName = game.rom_name
        ? game.rom_name.replace(/\.[a-zA-Z0-9]+$/, '')
        : game.title;
      const romFileName =
        game.rom_name ||
        `${game.title}.${this.getDefaultRomExtension(game.platform)}`;

      lines.push(`  <game name="${this.escapeXml(gameNodeName)}">`);
      lines.push(
        `    <description>${this.escapeXml(game.title)}</description>`,
      );
      if (game.release_date) {
        lines.push(
          `    <year>${this.escapeXml(game.release_date.slice(0, 4))}</year>`,
        );
      }
      if (game.display_name || game.platform) {
        lines.push(
          `    <manufacturer>${this.escapeXml(game.brand || 'Unknown')}</manufacturer>`,
        );
      }

      const crcAttr = game.rom_crc
        ? ` crc="${this.escapeXml(game.rom_crc)}"`
        : '';
      lines.push(`    <rom name="${this.escapeXml(romFileName)}"${crcAttr} />`);
      lines.push('  </game>');
    }

    lines.push('</datafile>');
    return lines.join('\n');
  }

  /**
   * Helper that formats a 2D array of string cells into RFC 4180 CSV text.
   */
  private formatCsvTable(table: string[][]): string {
    return table
      .map((row) =>
        row
          .map((cell) => {
            const str = cell ?? '';
            if (
              str.includes(',') ||
              str.includes('"') ||
              str.includes('\n') ||
              str.includes('\r')
            ) {
              return `"${str.replace(/"/g, '""')}"`;
            }
            return str;
          })
          .join(','),
      )
      .join('\r\n');
  }

  /**
   * Escapes special characters for XML nodes and attributes.
   */
  private escapeXml(unsafe: string | null | undefined): string {
    if (!unsafe) return '';
    return unsafe
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  private getDefaultRomExtension(platform: string | null | undefined): string {
    const p = (platform || '').toLowerCase();
    if (p.includes('game boy advance') || p.includes('gba')) return 'gba';
    if (p.includes('game boy') || p.includes('gbc') || p.includes('gb'))
      return 'gb';
    if (p.includes('super nintendo') || p.includes('snes')) return 'sfc';
    if (p.includes('nintendo entertainment') || p.includes('nes')) return 'nes';
    if (p.includes('nintendo 64') || p.includes('n64')) return 'z64';
    if (p.includes('nintendo 3ds') || p.includes('3ds')) return '3ds';
    if (p.includes('nintendo ds') || p.includes('nds')) return 'nds';
    if (p.includes('gamecube')) return 'rvz';
    if (p.includes('wii u')) return 'wua';
    if (p.includes('wii')) return 'rvz';
    if (p.includes('switch')) return 'xci';
    if (p.includes('playstation vita') || p.includes('vita')) return 'psv';
    if (p.includes('playstation portable') || p.includes('psp')) return 'iso';
    if (p.includes('playstation')) return 'chd';
    if (p.includes('genesis') || p.includes('mega drive')) return 'md';
    if (p.includes('dreamcast') || p.includes('saturn')) return 'chd';
    return 'bin';
  }

  private getOwnershipLabel(
    status: OwnershipStatus | number | undefined,
  ): string {
    switch (status) {
      case OwnershipStatus.Owned:
        return 'Owned';
      case OwnershipStatus.Seeking:
        return 'Seeking';
      case OwnershipStatus.Ordered:
        return 'Ordered';
      default:
        return 'Unowned';
    }
  }

  private getPlayStatusLabel(status: PlayStatus | number | undefined): string {
    switch (status) {
      case PlayStatus.Played:
        return 'Played';
      case PlayStatus.Playing:
        return 'Playing';
      case PlayStatus.Queued:
        return 'Queued';
      case PlayStatus.Paused:
        return 'Paused';
      case PlayStatus.Dropped:
        return 'Dropped';
      default:
        return 'Unplayed';
    }
  }

  /**
   * Browser-native download trigger using temporary Anchor element.
   */
  public triggerDownload(blob: Blob, filename: string): void {
    if (typeof window === 'undefined' || typeof document === 'undefined') {
      return;
    }
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }
}
