import { Injectable, signal, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { SwPush } from '@angular/service-worker';
import { firstValueFrom } from 'rxjs';
import {
  DealNotificationPreferences,
  PushSubscriptionPayload,
} from '../models/collection.models';

export const DEFAULT_DEAL_PREFERENCES: DealNotificationPreferences = {
  enabled: false,
  scope: 'seeking_only',
  minDiscountPct: 20,
  maxPriceCents: null,
  platformIds: [],
  stores: ['Best Buy', 'VGP', 'PNP Games'],
};

const STORAGE_KEY_PREFS = 'gagglog_deal_notification_prefs';
const STORAGE_KEY_ENDPOINT = 'gagglog_push_endpoint';

/**
 * NOTIFICATION SERVICE
 *
 * Manages Web Push subscriptions and user-configurable deal notification
 * preferences for the Gagglog Collection Tracker PWA.
 */
@Injectable({
  providedIn: 'root',
})
export class NotificationService {
  private readonly http = inject(HttpClient);
  private readonly router = inject(Router);
  private readonly swPush = inject(SwPush, { optional: true });

  public readonly isSupported = signal<boolean>(false);
  public readonly isSubscribed = signal<boolean>(false);
  public readonly permissionState = signal<NotificationPermission>('default');
  public readonly preferences = signal<DealNotificationPreferences>(
    DEFAULT_DEAL_PREFERENCES,
  );
  public readonly isProcessing = signal<boolean>(false);
  public readonly currentEndpoint = signal<string | null>(null);

  constructor() {
    this.init();
  }

  private init(): void {
    // Check Web Push support in current browser / PWA context
    const supported =
      typeof window !== 'undefined' &&
      'serviceWorker' in navigator &&
      'PushManager' in window &&
      Boolean(this.swPush?.isEnabled);

    this.isSupported.set(Boolean(supported));

    if (typeof window !== 'undefined' && 'Notification' in window) {
      this.permissionState.set(Notification.permission);
    }

    // Load persisted local preferences
    if (typeof window !== 'undefined' && window.localStorage) {
      try {
        const storedPrefs = localStorage.getItem(STORAGE_KEY_PREFS);
        if (storedPrefs) {
          const parsed = JSON.parse(storedPrefs);
          this.preferences.set({ ...DEFAULT_DEAL_PREFERENCES, ...parsed });
        }

        const storedEndpoint = localStorage.getItem(STORAGE_KEY_ENDPOINT);
        if (storedEndpoint) {
          this.currentEndpoint.set(storedEndpoint);
          this.isSubscribed.set(true);
        }
      } catch (err) {
        console.warn('Failed to load notification preferences:', err);
      }
    }

    // Subscribe to notification clicks for routing
    if (this.swPush?.isEnabled) {
      this.swPush.notificationClicks.subscribe(({ notification }) => {
        const url = notification.data?.url;
        if (url) {
          this.router.navigateByUrl(url);
        }
      });
    }
  }

  /**
   * Requests push notification permission and registers subscription with edge worker.
   */
  public async enableNotifications(): Promise<boolean> {
    if (!this.isSupported()) {
      return false;
    }

    this.isProcessing.set(true);

    try {
      // 1. Fetch VAPID public key from backend
      const { publicKey } = await firstValueFrom(
        this.http.get<{ publicKey: string }>(
          '/api/notifications/vapid-public-key',
        ),
      );

      if (!publicKey) {
        throw new Error('VAPID public key not found from server');
      }

      // 2. Request browser push subscription
      if (!this.swPush) {
        throw new Error('SwPush service worker integration is not available');
      }
      const sub = await this.swPush.requestSubscription({
        serverPublicKey: publicKey,
      });

      const subJson = sub.toJSON();
      const p256dh = subJson.keys?.['p256dh'];
      const auth = subJson.keys?.['auth'];
      if (!sub.endpoint || !p256dh || !auth) {
        throw new Error('Invalid subscription keys generated by browser');
      }

      const activePrefs = {
        ...this.preferences(),
        enabled: true,
      };

      const payload: PushSubscriptionPayload = {
        endpoint: sub.endpoint,
        keys: {
          p256dh,
          auth,
        },
        preferences: activePrefs,
      };

      // 3. Register with backend
      await firstValueFrom(
        this.http.post<{ success: boolean }>(
          '/api/notifications/subscribe',
          payload,
        ),
      );

      // 4. Update local state
      this.isSubscribed.set(true);
      this.currentEndpoint.set(sub.endpoint);
      this.preferences.set(activePrefs);
      if (typeof window !== 'undefined' && 'Notification' in window) {
        this.permissionState.set(Notification.permission);
      }

      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem(STORAGE_KEY_ENDPOINT, sub.endpoint);
        localStorage.setItem(STORAGE_KEY_PREFS, JSON.stringify(activePrefs));
      }

      return true;
    } catch (err) {
      console.error('Failed to enable push notifications:', err);
      if (typeof window !== 'undefined' && 'Notification' in window) {
        this.permissionState.set(Notification.permission);
      }
      return false;
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Unsubscribes from push notifications.
   */
  public async disableNotifications(): Promise<boolean> {
    this.isProcessing.set(true);
    const endpoint = this.currentEndpoint();

    try {
      if (this.swPush?.isEnabled) {
        await this.swPush.unsubscribe();
      }

      if (endpoint) {
        await firstValueFrom(
          this.http.post<{ success: boolean }>(
            '/api/notifications/unsubscribe',
            { endpoint },
          ),
        );
      }

      const updatedPrefs = { ...this.preferences(), enabled: false };
      this.isSubscribed.set(false);
      this.currentEndpoint.set(null);
      this.preferences.set(updatedPrefs);

      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.removeItem(STORAGE_KEY_ENDPOINT);
        localStorage.setItem(STORAGE_KEY_PREFS, JSON.stringify(updatedPrefs));
      }

      return true;
    } catch (err) {
      console.error('Failed to unsubscribe from notifications:', err);
      return false;
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Updates notification filter dimensions and syncs with edge worker if subscribed.
   */
  public async updatePreferences(
    prefs: DealNotificationPreferences,
  ): Promise<boolean> {
    this.isProcessing.set(true);

    try {
      this.preferences.set(prefs);

      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem(STORAGE_KEY_PREFS, JSON.stringify(prefs));
      }

      const endpoint = this.currentEndpoint();
      if (this.isSubscribed() && endpoint) {
        await firstValueFrom(
          this.http.put<{ success: boolean }>(
            '/api/notifications/preferences',
            {
              endpoint,
              preferences: prefs,
            },
          ),
        );
      }

      return true;
    } catch (err) {
      console.error('Failed to save notification preferences:', err);
      return false;
    } finally {
      this.isProcessing.set(false);
    }
  }

  /**
   * Sends an immediate test alert to this device.
   */
  public async sendTestAlert(): Promise<boolean> {
    const endpoint = this.currentEndpoint();
    if (!endpoint) {
      return false;
    }

    this.isProcessing.set(true);
    try {
      const res = await firstValueFrom(
        this.http.post<{ success: boolean }>('/api/notifications/test', {
          endpoint,
        }),
      );
      return Boolean(res.success);
    } catch (err) {
      console.error('Failed to send test notification:', err);
      return false;
    } finally {
      this.isProcessing.set(false);
    }
  }
}
