name = "collection-tracker"
compatibility_date = "2024-04-12"
main = "src/worker.ts"

[assets]
directory = "dist/tracker/browser"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "collection-db"
database_id = "1e5eedbd-58d6-443e-a15e-568577cd5596"
