name = "collection-tracker"
pages_build_output_dir = "dist/tracker/browser"
compatibility_date = "2024-04-12"

[[d1_databases]]
binding = "DB"
database_name = "collection-db"
database_id = "local-collection-db"
