/**
 * RECONCILIATION APPLICATION TOOL (TS)
 * 
 * This tool parses the 'discovery_report.md' generated by the scraper 
 * and applies any user-marked changes ([x], [o], or [r]) directly to 
 * the local SQLite database.
 */

import Database from 'better-sqlite3';
import * as fs from 'fs';

const db = new Database('collection.sqlite');

interface CurrentSectionGame {
    title: string;
    platform: string;
}

/**
 * UTILITY: normalizeTitle
 * 
 * Consistent normalization for matching report items to database records.
 */
function normalizeTitle(title: string): string {
    if (!title) return '';
    return title.toLowerCase()
        .replace(/[–—]/g, '-')
        .replace(/[\(\)\-:]/g, ' ')
        .replace(/[^a-z0-9]/g, '')
        .trim();
}

/**
 * CORE EXECUTION: applyChanges
 */
async function applyChanges(): Promise<void> {
    const reportPath = 'discovery_report.md';
    if (!fs.existsSync(reportPath)) {
        console.error('No discovery_report.md found.');
        return;
    }

    const content = fs.readFileSync(reportPath, 'utf8');
    const lines = content.split('\n');

    let currentSectionGame: CurrentSectionGame | null = null;
    let addedCount = 0;
    let ignoredCount = 0;
    let updatedCount = 0;
    let currentLineContext: 'Games' | 'Figures' | 'Unmatched' | 'Sync' | null = null;
    let currentSeries: string | null = null;

    console.log('--- Applying Discovery Changes ---');

    for (const line of lines) {
        // Detect Section Context
        if (line.startsWith('## Action Required: Sync Suggestions')) {
            currentLineContext = 'Sync';
            continue;
        } else if (line.startsWith('## Action Required: Unmatched Items')) {
            currentLineContext = 'Unmatched';
            continue;
        } else if (line.startsWith('## Discovery: New Games')) {
            currentLineContext = 'Games';
            continue;
        } else if (line.startsWith('## Discovery: New Figures')) {
            currentLineContext = 'Figures';
            continue;
        }

        // Detect Sub-sections (Game or Series)
        if (line.startsWith('### Series: ')) {
            currentSeries = line.replace('### Series: ', '').trim();
            continue;
        } else if (line.startsWith('### Line: ')) {
            currentSeries = line.replace('### Line: ', '').trim();
            continue;
        } else if (line.startsWith('### ')) {
            const gameMatch = line.match(/### (.*) \((.*)\)/);
            if (gameMatch) {
                currentSectionGame = { title: gameMatch[1].trim(), platform: gameMatch[2].trim() };
            }
            continue;
        }

        const isAdd = line.startsWith('- [x]');
        const isOwned = line.startsWith('- [o]');
        const isIgnore = line.startsWith('- [r]');
        const isActionable = isAdd || isOwned;

        if (isActionable) {
            // Check for Sync Suggestions format: "- [o] **Update to:** Suggested (Platform) - ID: igdb-ID"
            const syncMatch = line.match(/- \[[xo]\] \*\*(?:Update to|Link to):\*\* (.*) - ID: (.*)/);
            if (syncMatch) {
                const suggestedRaw = syncMatch[1].match(/(.*) \((.*)\)/) || [null, syncMatch[1], null];
                const newName = suggestedRaw[1]?.trim() || '';
                const id = syncMatch[2];

                if (currentSectionGame) {
                    const localId = id.replace('igdb-', '').replace('fig-', '');
                    
                    if (id.startsWith('igdb-')) {
                        const existing = db.prepare(`
                            SELECT g.id, p.display_name as platform
                            FROM games g
                            JOIN platforms p ON g.platform_id = p.id
                            WHERE g.title = ? AND p.display_name = ?
                        `).get(currentSectionGame.title, currentSectionGame.platform) as { id: number } | undefined;

                        if (existing) {
                            db.prepare('UPDATE games SET title = ?, igdb_id = ?, region = ?, owned = 1 WHERE id = ?')
                                .run(newName, localId, 'NA', existing.id);
                            console.log(`  Synced Game: "${currentSectionGame.title}" (${currentSectionGame.platform}) -> "${newName}" [ID: ${localId}]`);
                            updatedCount++;
                        }
                    }
                }
                continue;
            }

            // Normal ADD/Discovery logic
            const itemMatch = line.match(/- \[[xo]\] \*\*(.*)\*\* \((.*) (.*)\) - ID: (.*)/) || 
                             line.match(/- \[[xo]\] \*\*(.*)\*\* \(.*\) - ID: (.*)/);
            
            if (itemMatch) {
                const name = itemMatch[1];
                const id = itemMatch[4] || itemMatch[2];
                const type = itemMatch[3] || 'Figure';
                const ownedStatus = isOwned ? 1 : 0;
                const normName = normalizeTitle(name);

                if (currentLineContext === 'Games' && currentSeries) {
                    const existing = (db.prepare('SELECT id, title FROM games').all() as { id: number, title: string }[])
                        .find(g => normalizeTitle(g.title) === normName);
                    
                    if (existing) {
                        db.prepare('UPDATE games SET title = ?, owned = ? WHERE id = ?').run(name, ownedStatus, existing.id);
                        console.log(`  Updated existing Game: "${existing.title}" -> "${name}"`);
                        updatedCount++;
                    } else {
                        // Assuming new games from collection discovery come as 'igdb-...'
                        const cleanId = id.replace('igdb-', '');
                        db.prepare(`
                            INSERT OR IGNORE INTO games (id, title, series, platform, owned, queued, region) 
                            VALUES (?, ?, ?, ?, ?, 0, 'WW')
                        `).run(cleanId, name, currentSeries, 'Multiple Platforms', ownedStatus);
                        addedCount++;
                    }
                } else if (currentLineContext === 'Figures' && currentSeries) {
                    const s = db.prepare('SELECT id FROM figure_series WHERE name = ?').get(currentSeries) as { id: number } | undefined;
                    if (s) {
                        const existing = (db.prepare('SELECT id, name FROM figures WHERE series_id = ?').all(s.id) as { id: number, name: string }[])
                            .find(f => normalizeTitle(f.name) === normName);
                        
                        if (existing) {
                            db.prepare('UPDATE figures SET name = ?, owned = ?, type = ? WHERE id = ?').run(name, ownedStatus, type, existing.id);
                            console.log(`  Updated existing Figure: "${existing.name}" -> "${name}" (${type})`);
                            updatedCount++;
                        } else {
                            db.prepare(`
                                INSERT OR IGNORE INTO figures (id, name, line, series_id, owned, type)
                                VALUES (?, ?, ?, ?, ?, ?)
                            `).run(id, name, 'amiibo', s.id, ownedStatus, type);
                            addedCount++;
                        }
                    }
                }
            }
        } else if (isIgnore) {
            const itemMatch = line.match(/- \[r\] \*\*(.*)\*\* \(.*\) - ID: (.*)/);
            if (itemMatch) {
                const name = itemMatch[1];
                const id = itemMatch[2];
                db.prepare('INSERT OR IGNORE INTO ignored_items (id, type, reason) VALUES (?, ?, ?)').run(id, currentLineContext || 'Manual', 'User Rejected');
                console.log(`  Ignored: ${name}`);
                ignoredCount++;
            }
        }
    }

    console.log(`\nApply Complete! Added: ${addedCount}, Updated: ${updatedCount}, Ignored: ${ignoredCount}`);
}

applyChanges();
